# Generated by Django 4.1.5 on 2023-05-08 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='attendencemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.IntegerField()),
                ('empimg', models.ImageField(upload_to='')),
                ('empfname', models.CharField(max_length=50)),
                ('emplname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('empid', models.CharField(max_length=10)),
                ('totaldays', models.IntegerField()),
                ('presentdays', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='documentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.IntegerField()),
                ('empimg', models.ImageField(upload_to='')),
                ('empfname', models.CharField(max_length=50)),
                ('emplname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('empid', models.CharField(max_length=10)),
                ('appointorder', models.FileField(upload_to='employeeapp/static')),
                ('joinorder', models.FileField(upload_to='employeeapp/static')),
                ('appraisalorder', models.FileField(upload_to='employeeapp/static')),
            ],
        ),
        migrations.CreateModel(
            name='empbiodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('fathername', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('education', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='empleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=10)),
                ('fromdate', models.CharField(max_length=20)),
                ('todate', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('response', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employeeaddmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empimg', models.FileField(upload_to='employeeapp/static')),
                ('empfname', models.CharField(max_length=50)),
                ('emplname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10)),
                ('department', models.CharField(choices=[('Administrative', 'Administrative'), ('Human Resource', 'Human Resource'), ('Operations', 'Operations'), ('Purchasing', 'Purchasing'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Accounting', 'Accounting'), ('Finance', 'Finance'), ('Information Technology', 'Information Technology')], max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50)),
                ('dob', models.CharField(max_length=20)),
                ('empid', models.CharField(max_length=10)),
                ('dateofjoining', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='noticemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('notes', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='payrollmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.IntegerField()),
                ('empimg', models.ImageField(upload_to='')),
                ('empfname', models.CharField(max_length=50)),
                ('emplname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('empid', models.CharField(max_length=10)),
                ('basicsalary', models.IntegerField()),
                ('allowance', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='shiftmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.IntegerField()),
                ('empid', models.CharField(max_length=10)),
                ('shiftdate', models.CharField(max_length=20)),
                ('shifttime', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='taskmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=10)),
                ('task', models.CharField(max_length=250)),
                ('assigndate', models.DateField()),
                ('submitdate', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted')], default='Pending', max_length=50)),
                ('employeeid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
