# Generated by Django 4.1.5 on 2023-05-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_rename_taskmodel_taskmodel2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='taskmodel2',
        ),
    ]
