# Generated by Django 4.1.5 on 2023-05-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_taskmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmode',
            name='assigndate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
