# Generated by Django 4.1.5 on 2023-05-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0005_alter_taskmode_assigndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleave',
            name='fromdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empleave',
            name='todate',
            field=models.DateField(),
        ),
    ]
