# Generated by Django 4.1.5 on 2023-05-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0006_alter_empleave_fromdate_alter_empleave_todate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollmodel',
            name='empfname',
        ),
        migrations.RemoveField(
            model_name='payrollmodel',
            name='empimg',
        ),
        migrations.RemoveField(
            model_name='payrollmodel',
            name='emplname',
        ),
    ]
